# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import transactionapi_pb2 as transactionapi__pb2


class TransactionApiStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTransaction = channel.unary_unary(
        '/transactionapi.TransactionApi/CreateTransaction',
        request_serializer=transactionapi__pb2.Transaction.SerializeToString,
        response_deserializer=transactionapi__pb2.TransactionReply.FromString,
        )
    self.GetTransaction = channel.unary_unary(
        '/transactionapi.TransactionApi/GetTransaction',
        request_serializer=transactionapi__pb2.TransactionRequest.SerializeToString,
        response_deserializer=transactionapi__pb2.Transaction.FromString,
        )


class TransactionApiServicer(object):

  def CreateTransaction(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransaction(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransactionApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTransaction,
          request_deserializer=transactionapi__pb2.Transaction.FromString,
          response_serializer=transactionapi__pb2.TransactionReply.SerializeToString,
      ),
      'GetTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransaction,
          request_deserializer=transactionapi__pb2.TransactionRequest.FromString,
          response_serializer=transactionapi__pb2.Transaction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'transactionapi.TransactionApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
