# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transactionapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transactionapi.proto',
  package='transactionapi',
  syntax='proto3',
  serialized_pb=_b('\n\x14transactionapi.proto\x12\x0etransactionapi\"Q\n\x0bTransaction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04\x66rom\x18\x03 \x01(\r\x12\n\n\x02to\x18\x04 \x01(\r\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x01\"#\n\x10TransactionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x12TransactionRequest\x12\n\n\x02id\x18\x01 \x01(\r2\xbb\x01\n\x0eTransactionApi\x12T\n\x11\x43reateTransaction\x12\x1b.transactionapi.Transaction\x1a .transactionapi.TransactionReply\"\x00\x12S\n\x0eGetTransaction\x12\".transactionapi.TransactionRequest\x1a\x1b.transactionapi.Transaction\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='transactionapi.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='transactionapi.Transaction.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='transactionapi.Transaction.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from', full_name='transactionapi.Transaction.from', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='transactionapi.Transaction.to', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='transactionapi.Transaction.amount', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=121,
)


_TRANSACTIONREPLY = _descriptor.Descriptor(
  name='TransactionReply',
  full_name='transactionapi.TransactionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='transactionapi.TransactionReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=158,
)


_TRANSACTIONREQUEST = _descriptor.Descriptor(
  name='TransactionRequest',
  full_name='transactionapi.TransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='transactionapi.TransactionRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['TransactionReply'] = _TRANSACTIONREPLY
DESCRIPTOR.message_types_by_name['TransactionRequest'] = _TRANSACTIONREQUEST

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'transactionapi_pb2'
  # @@protoc_insertion_point(class_scope:transactionapi.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)

TransactionReply = _reflection.GeneratedProtocolMessageType('TransactionReply', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONREPLY,
  __module__ = 'transactionapi_pb2'
  # @@protoc_insertion_point(class_scope:transactionapi.TransactionReply)
  ))
_sym_db.RegisterMessage(TransactionReply)

TransactionRequest = _reflection.GeneratedProtocolMessageType('TransactionRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONREQUEST,
  __module__ = 'transactionapi_pb2'
  # @@protoc_insertion_point(class_scope:transactionapi.TransactionRequest)
  ))
_sym_db.RegisterMessage(TransactionRequest)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class TransactionApiStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CreateTransaction = channel.unary_unary(
          '/transactionapi.TransactionApi/CreateTransaction',
          request_serializer=Transaction.SerializeToString,
          response_deserializer=TransactionReply.FromString,
          )
      self.GetTransaction = channel.unary_unary(
          '/transactionapi.TransactionApi/GetTransaction',
          request_serializer=TransactionRequest.SerializeToString,
          response_deserializer=Transaction.FromString,
          )


  class TransactionApiServicer(object):

    def CreateTransaction(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_TransactionApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateTransaction': grpc.unary_unary_rpc_method_handler(
            servicer.CreateTransaction,
            request_deserializer=Transaction.FromString,
            response_serializer=TransactionReply.SerializeToString,
        ),
        'GetTransaction': grpc.unary_unary_rpc_method_handler(
            servicer.GetTransaction,
            request_deserializer=TransactionRequest.FromString,
            response_serializer=Transaction.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'transactionapi.TransactionApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaTransactionApiServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def CreateTransaction(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetTransaction(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaTransactionApiStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def CreateTransaction(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    CreateTransaction.future = None
    def GetTransaction(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetTransaction.future = None


  def beta_create_TransactionApi_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('transactionapi.TransactionApi', 'CreateTransaction'): Transaction.FromString,
      ('transactionapi.TransactionApi', 'GetTransaction'): TransactionRequest.FromString,
    }
    response_serializers = {
      ('transactionapi.TransactionApi', 'CreateTransaction'): TransactionReply.SerializeToString,
      ('transactionapi.TransactionApi', 'GetTransaction'): Transaction.SerializeToString,
    }
    method_implementations = {
      ('transactionapi.TransactionApi', 'CreateTransaction'): face_utilities.unary_unary_inline(servicer.CreateTransaction),
      ('transactionapi.TransactionApi', 'GetTransaction'): face_utilities.unary_unary_inline(servicer.GetTransaction),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_TransactionApi_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('transactionapi.TransactionApi', 'CreateTransaction'): Transaction.SerializeToString,
      ('transactionapi.TransactionApi', 'GetTransaction'): TransactionRequest.SerializeToString,
    }
    response_deserializers = {
      ('transactionapi.TransactionApi', 'CreateTransaction'): TransactionReply.FromString,
      ('transactionapi.TransactionApi', 'GetTransaction'): Transaction.FromString,
    }
    cardinalities = {
      'CreateTransaction': cardinality.Cardinality.UNARY_UNARY,
      'GetTransaction': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'transactionapi.TransactionApi', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
